---
title: "Carga de DF"
author: "Sebastian Landeo"
date: "2024-07-22"
output: html_document
---
```{r}
df = read.table("../../data/bulls.dat",
                header = FALSE,
                col.names = c("breed", "sale_price", "shoulder",
                              "fat_free", "percent_ff", "frame_scale",
                              "back_fat", "sale_height", "sale_weight"),
                sep = "", dec = ".")
head(df)
```
# Obteniendo un DF desde la web
```{r}
library(RCurl)
# Obtener el archivo de datos desde la URL correcta
# Incorrecto="https://archive.ics.uci.edu/dataset/2/adult"
url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
data <- getURL(url)

# Leer el archivo de datos en un dataframe
df3 <- read.table(textConnection(data), sep = ",", header = FALSE, strip.white = TRUE)
colnames(df3) <- c("age", "workclass", "fnlwgt", "education", "education_num",
                   "marital_status", "occupation", "relationship", "race",
                   "sex", "capital_gain", "capital_loss", "hours_per_week",
                   "native_country", "income")

# Mostrar las primeras filas del dataframe
head(df3)
str(df3)
```
# Guardar un DF
```{r}
write.table(df3, file="../../data/adult.text", dec=".")
df4 = read.table("../../data/adult.text", dec=".")
head(df4)
str(df4)
```
# Construyendo data frames
```{r}
Algebra = c(1,2,0,5,4,6,7,5,5,8)
Analysis = c(3,3,2,7,9,5,6,8,5,6)
Statistics = c(4,5,4,8,8,9,6,7,9,10)
grades = data.frame(Algebra, Analysis, Statistics)
str(grades)
# Continuación agregando una nueva columna
Calculus = c(5, 4, 6, 2, 1, 0, 7, 8, 9, 6)
grades2 = cbind(grades, Calculus)
head(grades2)
```
```{r}
genero = c("Hombre","Mujer","Hombre","Mujer")
edad = c(25,35,28,30)
hijos = c(1,3,2,2)
df5 = data.frame(genero, edad, hijos, stringsAsFactors = TRUE)
fix(df5)
names(df5)=c("gender", "Age", "Sons")
rownames(df5)=c("P1","P2","P3","P4")
dimnames(df5)=list(
  c("Antonio", "Ricarda", "JuanGabriel", "Maria"),
  c("Sexo", "Años", "MiembrosFamilia")
)
df5 = rbind(df5, c("Hombre", 30, 1))
df5$Sexo = as.character(df5$Sexo)
str(df5)
df5$Ingresos = c(10000, 12000, 15000, 12000, 20000)
df5
```

```{r}
genero = c("Hombre","Mujer","Hombre","Mujer")
edad =   c(     25,      35,      28,     30)
hijos =  c(      1,       3,       2,      2)
df5 = data.frame(genero, edad, hijos, stringsAsFactors = TRUE)
df5[df5$genero=="Mujer", ] -> df_m
df_m = droplevels(df_m)
str(df_m)
```
#Tidyverse
```{r}
library(tidyverse)
iris_petal = select(iris, starts_with("Petal"))
head(iris_petal)
iris_lenght = select(iris, ends_with("Length"))
head(iris_lenght)
```
#Subset
```{r}
subset(iris, Species == "versicolor", select = c(1,3)) -> versicolor
rownames(versicolor) = 1:nrow(versicolor)
head(versicolor, 5)
str(versicolor)
```



