---
title: "Datos Cuantitativos Agrupados"
author: "Sebastian Landeo"
date: "2024-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Implementando las reglas de agrupación
```{r}
crabs = read.table("../data/datacrab.txt", header = TRUE)
str(crabs)
head(crabs)
crabs$width
```
#### Manera larga
##### Regla de la raíz cuadrada
```{r}
n = length(cw)
k1 = ceiling(sqrt(n))
k1
```
#### Regla de Sturges
```{r}
k2 = ceiling(1+log(n,2))
k2
```
#### Regla de Scott
```{r}
As = 3.5*sd(cw)*n^(-1/3)
k3 = ceiling(diff(range(cw))/As)
k3
```
#### Regla de Freedman-Diaconis
```{r}
Afd = 2*(quantile(cw, 0.75, names= FALSE)-quantile(cw, 0.25, names=FALSE))*n^(-1/3)
k4 = ceiling(diff(range(cw))/Afd)
k4
```
### Usando las funciónes de R
```{r}
nclass.Sturges(cw)
nclass.scott(cw)
nclass.FD(cw)
```
### Amplitud de los intervalos
```{r}
A = diff(range(cw))/10
A
A = 1.3
```
### Calcular el extremo de los intervalos
```{r}
L1 = min(cw)-1/2*0.1
L1
L = L1 + A*(0:10)
L
```
### Hallar la marca de clase
```{r}
X1 = (L[1]+L[2])/2
X1
X = X1 + A*(0:9)
X
X = (L[1:length(L)-1]+L[2:length(L)])/2
X
```