---
title: "Ejemplo final"
author: "Sebastian Landeo"
date: "2024-08-01"
output: html_document
---

# Ejemplo final

## Juntar color de ojos y pelo sin sexo
```{r}
ftable(HairEyeColor)
male <- HairEyeColor[,,"Male"]
ftable(male)
female <- HairEyeColor[,,"Female"]
ftable(female)
data <- as.table(male + female)
data
```
## Manipulación de datos
```{r}
dimnames(data) = list(
  Pelo = c("Negro","Marron","Rojo", "Rubio"), 
  Ojos = c("Marrones", "Azules", "Pardos", "Verdes"))
data
```
## Gráfico de mosaico
```{r}
plot(data, main="Gráfico de mosaico")
```
```{r}
sum(data)
colSums(data)
rowSums(data)
round(prop.table(colSums(data)), 3)
round(prop.table(rowSums(data)), 3)
```
```{r}
par(mfrow=c(1,2))
barplot(prop.table(colSums(data)), 
        col=c("burlywood4","lightblue","orange3","lightgreen"),
        main="Frecuencias relativas\nde colores de ojos",
        ylim = c(0, 0.4),
        cex.names=0.7)
barplot(prop.table(rowSums(data)), col=c("black","brown","red","yellow"),
        main="Frecuencias relativas\nde colores de cabello",
        ylim = c(0, 0.5),
        cex.names=0.7)
```
```{r}
barplot(round(prop.table(colSums(data)), 3),
        col=c("brown", "lightblue", "orange", "green"),
        main="Frecuencias relativas\nde colores de ojos",
        names.arg=c("Marrones", "Azules", "Pardos", "Verdes")  # Especificar etiquetas
)
```
```{r}
data
prop.table(data)
prop.table(data, margin = 1)
prop.table(data, margin = 2)
```
```{r}
par(mfrow=c(1,2))
barplot(prop.table(data, margin = 1),beside = TRUE, legend.text = TRUE,
        main = "Frecuencias relativas de colores de cabello en cada color de ojos",
        col=c("black","brown","red","yellow"),
        ylim = c(0,0.8),
        cex.names=0.7
        )
barplot(t(prop.table(data, margin = 2)),beside = TRUE, legend.text = TRUE,
        main = "Frecuencias relativas de colores de ojo en cada color de cabellos",
        col=c("brown", "lightblue", "orange", "green"),
        ylim = c(0,0.6),
        cex.names=0.7
        )
```


