---
title: "Datos ordinales"
author: "Sebastian Landeo"
date: "2024-08-04"
output: html_document
---
```{r}
notas = ordered(c("S", "A", "N", "Ex", "S", "S", "Ex", "Ex", "N", "A", "A", "A",
                  "A", "N", "S"), levels=c("S","A","N","Ex"))
table(notas)
```
```{r}
# set.seed(2018)
# clientes = sample(1:5, 50, replace = TRUE)
clientes = c(1, 2, 3, 1, 3, 4, 1, 3, 4, 5, 2, 4, 5, 4, 2, 5, 3, 1, 4, 2, 5, 3, 1, 4, 2, 5, 3, 1, 5, 3, 1, 5, 3, 6, 4, 1, 3, 5, 4, 3, 4, 1, 5, 1, 4)
clientes
# set.seed(NULL)
table(clientes)
```
```{r}
notas
fAbs = table(notas)
cumsum(fAbs)
```
```{r}
cumsum(prop.table(fAbs))
barplot(fAbs, main = "Diagrama de barras de frecuencias absolutas")
barplot(cumsum(fAbs), main = "Diagrama de barras de frecuencias absolutas")
```
```{r}
table(notas)
cumsum(table(notas))/length(notas)
cumsum(table(notas)/length(notas))
cumsum(table(notas))
prop.table(cumsum(table(notas)))
```
```{r}
longitud = sample(c("Muy.corto", "Corto", "Normal", "Largo", "Muy Largo"), 100, replace = TRUE)
longitud = ordered(longitud, levels=c("Muy.corto", "Corto", "Normal", "Largo", "Muy Largo"))
longitud
```
```{r}
table(longitud)
```
```{r}
zonas = rep(c("A", "B", "C", "D"), c(30, 25, 35, 10))
jirafas = data.frame(zonas, longitud)
str(jirafas)
head(jirafas)
```
```{r}
table(jirafas)
apply(table(jirafas), MARGIN = 1, FUN = cumsum)
t(apply(table(jirafas), MARGIN = 1, FUN = cumsum))
```
```{r}
table(jirafas)
prop.table(table(jirafas), margin=1)
t(apply(prop.table(table(jirafas), margin=1), MARGIN = 1, FUN = cumsum))
```
```{r}
barplot(t(prop.table(table(jirafas), margin=1)), beside = TRUE, legend = TRUE, args.legend=list(x="topleft", cex = 0.55), ylim=c(0,1.0))
```

```{r}
Diagrama = apply(prop.table(table(jirafas), margin = 1), MARGIN = 1, FUN = cumsum)
barplot(Diagrama, beside = TRUE, legend = TRUE, main = "Diagrama de barras de
        frecuencias relativas acumuladas de longitud por zonas",
        args.legend=list(x="topleft", cex = 0.55))
```
### Ejemplo 5
```{r}
crabs = read.table("../../data/datacrab.txt", header = TRUE)
crabs = crabs[,-1] #Omitimos la primera columna
str(crabs)
```
```{r}
table(crabs$width)
intervalos = cut(crabs$width, breaks = c(21, 25, 29, 33, Inf), right = FALSE,
                 labels = c("21-25", "25-29", "29-33", "33-..."))
intervalos
typeof(intervalos)
crabs$width.rank = ordered(intervalos)
str(crabs)
crabs
```
```{r}
Tabla = table(crabs[,c(1,6)])
Tabla
```
```{r}
Fr.rel = round(prop.table(Tabla, margin = 1), 3)
Fr.rel
```
```{r}
Fr.rel.acu = round(apply(prop.table(Tabla, margin = 1), MARGIN = 1, FUN = cumsum), 3)
t(Fr.rel.acu)
```
```{r}
azul = c("cyan", "cyan4", "cyan1", "cyan3")
barplot(t(Fr.rel), beside = TRUE, legend = TRUE, ylim = c(0,1), col=azul,
        main = "Diagrama de barra de frecuencias relativas",
        args.legend = list(x = "topright", cex = 0.55))
```
```{r}
barplot(Fr.rel.acu, beside = TRUE, legend = TRUE, ylim = c(0,1), col=azul,
        main = "Diagrama de barra de frecuencias relativas",
        args.legend = list(x = "topright", cex = 0.55))
```



